name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        env:
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
          REACT_APP_CRYPTO_RAPIDAPI_HOST: ${{ secrets.REACT_APP_CRYPTO_RAPIDAPI_HOST }}
          REACT_APP_CRYPTO_API_URL: ${{ secrets.REACT_APP_CRYPTO_API_URL }}
          REACT_APP_NEWS_RAPIDAPI_HOST: ${{ secrets.REACT_APP_NEWS_RAPIDAPI_HOST }}
          REACT_APP_NEWS_API_URL: ${{ secrets.REACT_APP_NEWS_API_URL }}
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build